apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hospital-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: healthcare-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "development"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
            - name: DNS_SERVERS
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DNS_SERVERS
