const ROLES = {
  PATIENT: "PATIENT",
  DOCTOR: "DOCTOR",
  ADMIN: "ADMIN"
};

const PUBLIC_REGISTRATION_ROLES = [ROLES.PATIENT, ROLES.DOCTOR];

module.exports = {
  ROLES,
  PUBLIC_REGISTRATION_ROLES
};
